import React from 'react'
import Head from 'next/head'
import { MainLayout } from '@/components/layout'
import HeadlineTag from '@/components/HeadlineTag'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <MainLayout>
        <FadeUpAnimation>
          <section className='px-4 py-25'>
            <div className='ct-container mx-auto'>
              <h1 className='text-4xl text-secondary text-center'>About</h1>
              <h4 className='text-lg mt-4 mb-10 text-center max-w-140 mx-auto'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.</h4>
              <img src='/images/banner-about.jpg' className='w-full h-auto lg:h-120 object-cover object-center' alt='about' />
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='max-w-235 mx-auto'>
              <div className='max-w-165 mx-auto text-center'>
                <HeadlineTag title='Introductions' />
                <h2 className='text-3xl text-secondary mb-4'>Overlaid the jeepers uselessly much excluding everyday life.</h2>
                <p>It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
              </div>

              <div className='my-15 sm:grid sm:grid-cols-2 sm:gap-6 sm:items-center'>
                <div>
                  <h3 className='text-2xl text-secondary mb-4'>Overlaid the jeepers uselessly much excluding everyday life.</h3>
                  <p className='mb-4'>It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                </div>
                <div className=''>
                  <img className='max-w-full' src='/images/about-img-1.jpg' alt='image' />
                </div>
              </div>

              <div className='sm:grid sm:grid-cols-2 sm:gap-6 sm:items-center'>
                <div>
                  <h3 className='text-2xl text-secondary mb-4'>Overlaid the jeepers uselessly much excluding everyday life.</h3>
                  <p className='mb-4'>It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                </div>
                <div className=''>
                  <img className='max-w-full' src='/images/about-img-2.jpg' alt='image' />
                </div>
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='max-w-235 mx-auto'>
              <HeadlineTag title='Introductions' />
              <div className='grid grid-cols-1 gap-10 sm:grid-cols-3 sm:gap-4'>
                <div className='text-center'>
                  <img className='w-full' src='/images/about-owner-1.jpg' alt='owner' />
                  <div className='text-secondary text-xl mt-4 mb-2'>Fred Gleason</div>
                  <div className='uppercase font-xs'>Brand Owner</div>
                </div>
                <div className='text-center'>
                  <img className='w-full' src='/images/about-owner-2.jpg' alt='owner' />
                  <div className='text-secondary text-xl mt-4 mb-2'>Isabel Hamill</div>
                  <div className='uppercase font-xs'>Mug Designer</div>
                </div>
                <div className='text-center'>
                  <img className='w-full' src='/images/about-owner-3.jpg' alt='owner' />
                  <div className='text-secondary text-xl mt-4 mb-2'>Maurice Herman</div>
                  <div className='uppercase font-xs'>Mug Designer</div>
                </div>
              </div>
            </div>
          </section>
        </FadeUpAnimation>
      </MainLayout>
    </>
  )
}