import Head from 'next/head'
import Link from 'next/link'

import { EmptyLayout } from '@/components/layout'
import Button from '@/components/common/Button'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'
import { ROUTES } from '@/constants'

export default function ThankyouPage() {
  return (
    <>
      <Head>
        <title>Thank you</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <EmptyLayout>
        <FadeUpAnimation>
          <section className='mx-auto h-screen w-screen bg-green-100 flex items-center justify-center relative'>
            <div className='fixed top-0 left-0 w-[50vw] h-[50vh] bg-amber-400 [clip-path:polygon(0_0,100%_0,0_100%)]' />
            <div className='text-center relative z-20 px-4'>
              <img src='/images/thank-you.png' className='max-w-full mx-auto' alt='thank-you' />
              <p className='mb-6 font-bold text-2xl'>Thank you for your shopping. We will contact you soon !!</p>
              <Link href={ROUTES.HOMEPAGE}><Button variant='primary' className='capitalize'>Back to homepage</Button></Link>
            </div>
            <div className='fixed bottom-0 right-0 w-[50vw] h-[50vh] bg-green-400 [clip-path:polygon(100%_100%,0_100%,100%_0)]' />
          </section>
        </FadeUpAnimation>
      </EmptyLayout>
    </>
  )
}