import React from 'react'
import Head from 'next/head'
import { MainLayout } from '@/components/layout'
import HeadlineTag from '@/components/HeadlineTag'
import Post from '@/components/blog/Post'
import Link from 'next/link'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'

export default function BlogPage() {
  return (
    <>
      <Head>
        <title>Our Blogs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MainLayout>
        <FadeUpAnimation>
          <section className='py-25 px-4'>
            <div className='ct-container mx-auto'>
              <h1 className='text-4xl text-secondary text-center'>Read coffee stories on our Blog</h1>
              <h4 className='text-lg mt-4 mb-10 text-center'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</h4>
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='ct-container mx-auto'>
              <HeadlineTag title='Hightlight post' />
              <div className='grid grid-cols-1 gap-4 sm:grid-cols-2'>
                <Post title='Health Check: why do I get a headache when I have not had my coffee?' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-1.jpg' />
                <Post title='How long does a cup of coffee keep you awake?' description='It is a paradisematic country, in which roasted parts. Vel qui et ad voluptatem.' date='October 9, 2018' thumb='/images/blogs/blog-2.jpg' />
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        <section className='px-4 pb-25'>
          <div className='ct-container mx-auto'>
            <div className='grid grid-cols-1 lg:grid-cols-[6fr_4fr] xl:grid-cols-[7fr_3fr] gap-4'>
              {/* Lastes post  */}
              <div>
                <h3 className='text-secondary text-2xl border-b border-b-[#ececed] pb-6 mb-6'>Latest Posts</h3>
                <div className='grid grid-cols-1 gap-4 sm:grid-cols-2'>
                  <Post title='Health Check: why do I get a headache when I have not had my coffee?' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-1.jpg' />
                  <Post title='How long does a cup of coffee keep you awake?' description='It is a paradisematic country, in which roasted parts. Vel qui et ad voluptatem.' date='October 9, 2018' thumb='/images/blogs/blog-2.jpg' />
                  <Post title='Recent research suggests that heavy coffee drinkers may reap health benefits. ' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-3.jpg' />
                  <Post title='Health Check: why do I get a headache when I have not had my coffee?' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-1.jpg' />
                </div>
              </div>

              {/* Sidebar post  */}
              <FadeUpAnimation>
                <div>
                  <h3 className='text-secondary text-2xl border-b border-b-[#ececed] pb-6 mb-6'>Categories</h3>
                  <ul>
                    <li><Link className='ct-category-item' href='#'>Barista</Link></li>
                    <li><Link className='ct-category-item' href='#'>Coffee</Link></li>
                    <li><Link className='ct-category-item' href='#'>Lifestyle</Link></li>
                    <li><Link className='ct-category-item' href='#'>Mugs</Link></li>
                  </ul>
                </div>
              </FadeUpAnimation>


            </div>
          </div>
        </section>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='ct-container mx-auto'>
              <p className='text-light-coffee text-xl text-center border-l border-b border-light-coffee/50 p-4 sm:p-9'>&quot;I wake up some mornings and sit and have my coffee and look out at my beautiful garden, and I go, ’Remember how good this is. Because you can lose it.&quot;</p>
              <p className='text-center font-bold mt-6'>Jason Johnson - Owner of CoffeeStyle</p>
            </div>
          </section>
        </FadeUpAnimation>
      </MainLayout>
    </>
  )
}