import { useState, useEffect } from 'react'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { object, string } from 'yup'
import { useForm, FormProvider } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import { toast } from 'react-toastify'

import InputField from '@/components/form/InputField'
import Button from '@/components/common/Button'
import { AdminLayout } from '@/components/layout'
import SwitchButton from '@/components/admin/SwitchButton'
import SelectField from '@/components/form/SelectField'
import { createLoadingSelector } from '@/store/loaderSlice'
import { CREATE_POST } from '@/store/postSlice'
import { createPost } from '@/store/postSlice'
import { getListCategories, selectListCategories } from '@/store/categorySlice'
import { stringHelpers } from '@/helpers'

const PostEditor = dynamic(
  () => import('@/components/admin/editor/PostEditor'),
  { ssr: false }
)

const CreatePostPage = () => {
  const dispatch = useDispatch()
  const loadingSelector = createLoadingSelector([CREATE_POST])
  const isLoading = useSelector((state) => loadingSelector(state.loader))
  const [highlight, setHighlight] = useState(false)
  const [published, setPublished] = useState(true)
  const categoriesFetch = useSelector(selectListCategories)
  const [categories, setCategories] = useState([])
  const [editor, setEditor] = useState(null)


  const schema = object({
    title: string().required('Please enter your title'),
    description: string().required('Please enter your description'),
    thumbnail: string().required('Please enter your thumbnail URL'),
    category: object({
      id: string().required(),
      name: string().required(),
      slug: string().required()
    })
      .nullable()
      .required('Please choose category')
      .test(
        'is-selected',
        'Please choose category',
        (value) => value && value.id
      )
  })

  const methods = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      title: '',
      description: '',
      content: '',
      thumbnail: '',
      category: {
        id: '',
        name: '',
        slug: ''
      }
    }
  })

  const { reset } = methods

  const onSubmit = async(data) => {
    try {
      const dataPost = {
        title: data.title,
        description: data.description,
        slug: stringHelpers.slugify(data.title),
        content: editor?.getData() || '',
        thumbnail: data.thumbnail,
        category: data.category,
        published,
        highlight
      }

      await dispatch(createPost(dataPost)).unwrap()

      toast.success('Post created!')
      reset()
      editor?.setData('')
      setPublished(true)
      setHighlight(false)

    } catch (error) {
      toast.error(error?.message)
    }
  }

  useEffect(() => {
    const options = (categoriesFetch || []).map(item => ({
      label: item.name,
      value: item._id,
      name: item._name
    }))
    setCategories(options)
  }, [categoriesFetch])

  useEffect(() => {
    dispatch(getListCategories())
  }, [dispatch])

  return (
    <>
      <Head>
        <title>Admin - Create Post</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <AdminLayout>
        <section>
          <h1 className='mb-6 text-3xl font-bold'>Create Post</h1>
          <FormProvider {...methods}>
            <form onSubmit={methods.handleSubmit(onSubmit)}>
              <div className='grid grid-cols-2 mb-4'>
                <div className='flex items-center'>
                  <span className='text-light-coffee mr-2'>Highlight</span>
                  <SwitchButton checked={highlight} onChange={() => setHighlight(!highlight)} />
                </div>
                <div className='flex items-center'>
                  <span className='text-light-coffee mr-2'>Published</span>
                  <SwitchButton checked={published} onChange={() => setPublished(!published)} />
                </div>
              </div>

              <div className='lg:grid lg:grid-cols-2 lg:gap-4'>
                <InputField
                  name='title'
                  label='Title'
                  labelClasses='text-left block'
                  inputClasses='bg-white'
                  required
                />
                <InputField
                  name='description'
                  label='Description'
                  labelClasses='text-left block'
                  inputClasses='bg-white'
                  required
                />
              </div>

              <div className='lg:grid lg:grid-cols-2 lg:gap-4'>
                <InputField
                  name='thumbnail'
                  label='Thumbnail URL'
                  labelClasses='text-left block'
                  inputClasses='bg-white'
                  required
                />
                <SelectField
                  name='category'
                  label='Category'
                  placeholder='Select category...'
                  options={categoriesFetch.map(item => ({
                    label: item.name,
                    value: item._id,
                    slug: item.slug
                  }))}
                  returnObject
                  mapValue={(opt) => ({
                    id: opt.value,
                    name: opt.label,
                    slug: opt.slug
                  })}
                  required
                />
              </div>

              <div>
                <p>Content</p>
                <PostEditor setEditor={setEditor} />
              </div>

              <Button loading={isLoading} type='submit' size='sm' variant='secondary' className='hover:bg-light-coffee hover:text-white uppercase mt-4'>{isLoading ? 'Saving...' : 'Save Post'}</Button>
            </form>
          </FormProvider>
        </section>
      </AdminLayout>
    </>
  )
}

export default CreatePostPage