import Head from 'next/head'
import Link from 'next/link'
import { EmptyLayout } from '@/components/layout'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'
import { ROUTES } from '@/constants'

export default function Custom404() {
  return (
    <>
      <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <EmptyLayout>
        <FadeUpAnimation>
          <div className='w-screen h-screen flex justify-center items-center'>
            <div className='text-center'>
              <img className='max-w-full w-full lg:w-200' src='/images/404.png' alt='404' />
              <p className='font-bold'>Page not found. Please come back to home page.</p>
              <Link href={ROUTES.HOMEPAGE} className='ct-button capitalize bg-light-coffee hover:bg-light-coffee-hover font-bold text-white px-6 py-3 mt-6 inline-block'>Back to home</Link>
            </div>
          </div>
        </FadeUpAnimation>
      </EmptyLayout>
    </>

  )
}