import React, { useState, useMemo } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector, useDispatch } from 'react-redux'
import { FormProvider, useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import { object, string } from 'yup'
import { toast } from 'react-toastify'
import { useRouter } from 'next/router'

import { priceHelpers } from '@/helpers'
import { closeCart } from '@/store/cartSlice'
import InputField from '@/components/form/InputField'
import { EmptyLayout } from '@/components/layout'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'

export default function CheckoutPage() {
  const dispatch = useDispatch()
  const router = useRouter()
  const carts = useSelector((state) => state.cart.items)
  const [discountCode, setDiscountCode] = useState('')
  const [discountValue, setDiscountValue] = useState(0)

  const schema = object({
    name: string().required('Please enter your name'),
    phone: string().required('Please enter your phone number').matches(/^[0-9]{10,11}$/, 'Phone number is invalid'),
    address: string().required('Please enter your address')
  })

  const methods = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      name: '',
      phone: '',
      address: ''
    }
  })

  const handleBack = () => {
    router.back()
    dispatch(closeCart())
  }

  const handleApplyDiscount = () => {
    if (discountCode === 'SALE10') {
      setDiscountValue(0.1) // 10%
      toast.success('Apply discount 10% successfully')
    } else if (discountCode === 'SAVE20') {
      setDiscountValue(20) // 20 USD
      toast.success('Apply discount 20 USD successfully')
    } else {
      setDiscountValue(0)
      toast.error('Invalid discount code')
    }
  }

  const subtotal = priceHelpers.handleTotalPrice(carts)

  // const total = () => {
  //   if (discountValue < 1) {
  //   // % discount
  //     return Math.round(subtotal * (1 - discountValue) * 100) / 100
  //   } else {
  //   // fixed discount
  //     return Math.max(0, subtotal - discountValue)
  //   }
  // }

  const totalPrice = useMemo(() => {
    if (discountValue < 1) {
      return Math.round(subtotal * (1 - discountValue) * 100) / 100
    } else {
      return Math.max(0, subtotal - discountValue)
    }
  }, [subtotal, discountValue])

  const onSubmit = (data) => console.log(data)

  return (
    <>
      <Head>
        <title>Checkout</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <EmptyLayout>
        <FadeUpAnimation>
          <section className='px-4 py-25 ct-container mx-auto'>
            <div className='ct-container mx-auto'>
              <FormProvider {...methods}>
                <form onSubmit={methods.handleSubmit(onSubmit)}>
                  <div className='lg:grid lg:grid-cols-[60%_40%] lg:gap-10'>
                    <div className='bg-white'>
                      <h2 className='text-3xl font-bold mb-4'>Your info</h2>
                      <div className=''>
                        <InputField
                          name="name"
                          label="Name"
                          labelClasses='text-light-coffee text-left block'
                          inputClasses='text-secondary'
                        />
                        <InputField
                          type='number'
                          name="phone"
                          label="Phone number"
                          labelClasses='text-light-coffee text-left block'
                          inputClasses='text-secondary'
                        />
                        <InputField
                          name="address"
                          label="Address"
                          labelClasses='text-light-coffee text-left block'
                          inputClasses='text-secondary'
                        />
                      </div>
                    </div>
                    <div className='bg-white'>
                      <h2 className='text-3xl font-bold mb-4'>Your cart</h2>
                      {
                        carts.length > 0 ?
                          carts.map((product, index) => <div key={index} className='item flex justify-between items-center mb-4'>
                            <div className='flex items-center'>
                              <div className='relative'>
                                <Image src={product?.image} className='object-center object-cover mr-2 rounded-md' width={50} height={50} alt='product' loading='eager' />
                                <span className='absolute right-0 top-0 inline-flex rounded-full text-white bg-light-coffee/80 w-5 h-5 justify-center items-center'>{product?.quantity}</span>
                              </div>
                              <div>{product?.name}</div>
                            </div>
                            <span className=''>{priceHelpers.handleSubPrice(product)} USD</span>
                          </div>)
                          : <p>Empty cart</p>
                      }
                      <div className='flex border border-light-coffee rounded-xl mt-4'>
                        <input
                          placeholder='Discount code'
                          className='px-4 py-2 w-[70%] outline-none focus:outline-none'
                          value={discountCode}
                          onChange={(e) => setDiscountCode(e.target.value)}
                        />
                        <button type='button' className='ct-button bg-light-coffee hover:bg-light-coffee-hover text-white w-[30%]' onClick={handleApplyDiscount}>Apply</button>
                      </div>
                      <div className='flex justify-between py-5'>
                        <span className='text-xl font-bold'>Total</span>
                        <span className='text-xl font-bold'>{totalPrice} USD</span>
                      </div>
                      <div className='sm:grid grid-cols-2 items-center gap-6'>
                        <button type='submit' className='ct-button bg-light-coffee hover:bg-light-coffee-hover text-white w-full py-3.25 sm:order-2'>Checkout</button>
                        <button type='button' className='ct-button bg-secondary hover:bg-secondary-hover text-white w-full py-3.25 mt-5 sm:mt-0 sm:order-1' onClick={handleBack}>Back</button>
                      </div>
                    </div>
                  </div>
                </form>
              </FormProvider>
            </div>
          </section>
        </FadeUpAnimation>
      </EmptyLayout>
    </>
  )
}