import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import clsx from 'clsx'
import { CiCircleMinus, CiCirclePlus } from 'react-icons/ci'
import { IoDiamond } from 'react-icons/io5'
import { FaRegLightbulb } from 'react-icons/fa'
import { useDispatch, useSelector } from 'react-redux'
import { useRouter } from 'next/router'

import { addToCart, openCart } from '@/store/cartSlice'
import { getProductDetailBySlug, getListProducts, selectCurrentProduct } from '@/store/productSlice'
import { ROUTES } from '@/constants'
import HeadlineTag from '@/components/HeadlineTag'
import Product from '@/components/product/Product'
import { MainLayout } from '@/components/layout'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'
import Button from '@/components/common/Button'


export default function ProductDetailPage() {
  const LIMIT = 4
  const router = useRouter()
  const slug = router.query.slug
  const dispatch = useDispatch()
  const [quantity, setQuantity] = useState(1)
  const currentProduct = useSelector(selectCurrentProduct)
  const [relatedProducts, setRelatedProducts] = useState([])

  const handleAddProductToCart = () => {
    dispatch(addToCart({
      product: currentProduct,
      quantity
    }))
    dispatch(openCart())
  }

  const handleUpdateQuantity = (type) => {
    if (type === 'plus') {
      setQuantity(prev => prev+1)
    } else {
      if (quantity === 1) return false
      setQuantity(prev => prev-1)
    }
  }

  useEffect(() => {
    if (!slug) return
    dispatch(getProductDetailBySlug({ slug }))
  }, [slug])

  useEffect(() => {
    if (!currentProduct?.category_slug) return
    const getRelatedProducts = async () => {
      try {
        const data = await dispatch(
          getListProducts({
            category_slug: currentProduct.category_slug,
            limit: LIMIT,
            exclude: currentProduct._id
          })
        ).unwrap()
        setRelatedProducts(data?.products)
      } catch (err) {
        //
      }
    }
    getRelatedProducts()
  }, [currentProduct])

  return (
    <>
      <Head>
        <title>Coffee Shop - {currentProduct?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainLayout>
        <FadeUpAnimation>
          <section className='pt-30 pb-15 px-4'>
            <div className='max-w-235 mx-auto'>
              <div className='sm:grid sm:grid-cols-2 sm:gap-4'>
                <div className='relative'>
                  <img className='w-full' src={currentProduct?.image} alt={currentProduct?.name} />
                  {currentProduct?.on_sale && <span className='absolute right-4 top-4 z-30 inline-block text-light-coffee bg-white rounded-sm px-4 py-1.5 text-base font-bold'>On Sale</span>}
                </div>
                <div className=''>
                  <h1 className='text-secondary text-4xl font-bold mt-4'>{currentProduct?.name}</h1>
                  <p className='text-lg my-7'>{currentProduct?.description}</p>
                  <div className='flex items-center'>
                    {currentProduct?.on_sale && <span className='text-light-coffee text-2xl font-bold mr-3'>{currentProduct?.promotion_price} USD</span>}
                    <span className={clsx(
                      currentProduct?.on_sale ? 'line-through opacity-70 text-xl' : 'text-2xl'
                    )}>{currentProduct?.origin_price} USD</span>
                  </div>
                  <div className='flex items-center mt-4'>
                    <div className='flex items-center'>
                      <button onClick={() => handleUpdateQuantity('minus')} className='cursor-pointer h-10'><CiCircleMinus size={22} color='#1d1f2e' /></button>
                      <div className='border border-secondary mx-2'>
                        <span className='w-10 h-10 flex justify-center items-center border-0.25 border-secondary font-bold'>{quantity}</span>
                      </div>
                      <button onClick={() => handleUpdateQuantity('plus')} className='cursor-pointer h-10'><CiCirclePlus size={22} color='#1d1f2e' /></button>
                    </div>
                    <Button variant='secondary' className='ml-4 px-10' onClick={handleAddProductToCart}>Add to cart</Button>
                  </div>
                </div>
              </div>
              <div className='mt-15'>
                <div className='uppercase mb-4 font-bold'>Details</div>
                <p>{currentProduct?.detail}</p>
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='sm:grid sm:grid-cols-2'>
            <img src='/images/products/product-detail.jpg' className='h-full object-center object-cover xl:h-125 xl:w-full' alt='img' />
            <div className='bg-secondary text-white py-20 text-center px-4 lg:text-left xl:pl-15'>
              <h3 className='text-2xl'>Handmade by <span className='font-bold'>CoffeeStyle</span>.</h3>
              <h5 className='text-lg opacity-90 xl:max-w-100'>The most versatile furniture system ever created. Designed to fit your life.</h5>
              <div className='my-10 lg:relative lg:pl-10'>
                <IoDiamond size={22} color='white' className='mx-auto lg:absolute lg:left-0 lg:top-1' />
                <div className='my-2 text-xl'>Premium Quality</div>
                <p className='opacity-90 xl:max-w-100'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in.</p>
              </div>
              <div className='lg:relative lg:pl-10'>
                <FaRegLightbulb size={22} color='white' className='mx-auto lg:absolute lg:left-0 lg:top-1' />
                <div className='my-2 text-xl'>Gentle to the Environment</div>
                <p className='opacity-90 xl:max-w-100'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in.</p>
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='px-4 py-25'>
            <div className='ct-container mx-auto'>
              <HeadlineTag title='You might also like these' />
              <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-4 sm:gap-6'>
                {
                  relatedProducts &&
                  relatedProducts?.map((product, index) =>
                    <Product
                      key={index}
                      name={product.name}
                      image={product.image}
                      originPrice={product.origin_price}
                      promotionPrice={product.promotion_price}
                      isOnSale={product.on_sale}
                      url={ROUTES.PRODUCTS_DETAIL_PAGE.replace(':slug', product.slug)}
                    />)
                }
              </div>
            </div>
          </section>
        </FadeUpAnimation>
      </MainLayout>
    </>
  )
}